spring:
#  datasource:
#    url: ${spring.datasource.url}
#    username: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    vault:
      client_id: ${spring.cloud.vault.client_id}
      client_secret: ${spring.cloud.vault.client_secret}
      uri: ${spring.cloud.vault.uri}
      api:
        base: ${spring.cloud.vault.api.base}
        org: ${spring.cloud.vault.api.org}
        proj: ${spring.cloud.vault.api.proj}